### ISSUE TITLE
FAILED: subprojects/libsigcplusplus/docs/docs/manual/html during gtkmm building in Ubuntu 22.04

### ISSUE THREAD

**Issue by raphael10-collab** [libsigcplusplus/libsigcplusplus#101]
raphy@raohy:~/gtkmm-4.8.0$ meson setup --prefix /usr --libdir lib your_builddir .
    The Meson build system
    Version: 1.3.0
    Source dir: /home/raphy/gtkmm-4.8.0
    Build dir: /home/raphy/gtkmm-4.8.0/your_builddir

For size limits I've put the entire output of `meson setup --prefix /usr --libdir lib your_builddir .` command in google drive : https://drive.google.com/file/d/1kvP_xitHnRaVyNmXLOy7ZBtjdP1zZyev/view?usp=drive_link

Execuing ninja got this error: 

    raphy@raohy:~/gtkmm-4.8.0/your_builddir$ ninja
    [125/2744] Generating subprojects/libsigcplusplus/docs/docs/manual/manual_html with a custom command
    FAILED: subprojects/libsigcplusplus/docs/docs/manual/html 
    /usr/bin/python3 /home/raphy/gtkmm-4.8.0/subprojects/libsigcplusplus/tools/tutorial-custom-cmd.py html ../subprojects/libsigcplusplus/docs/docs/manual/libsigc_manual.xml subprojects/libsigcplusplus/docs/docs/manual/html
    error : Unknown IO error
    warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
    cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
    [134/2744] Generating subprojects/libsigcplusplus/docs/docs/reference/html_and_tag with a custom command
    ninja: build stopped: subcommand failed.

How to make it work?

**Comment by kjellahl** [comment]
From the README.md file of gtkmm-documentation:
```
docs/tutorial/C/index-in.docbook and the built index.docbook files are
DocBook 5.0 documents. index.docbook requires these packages (Ubuntu names,
can have other names in other distros):
  * docbook5-xml
  * docbook-xsl

It may be possible to build without these packages, but it will be much slower.
The xmllint command is told to read files from http://docbook.org.
The xsltproc command is told to read files from http://docbook.sourceforge.net.
The commands first search for local copies of those files. If local copies exist
and are installed at expected locations, the commands make no network accesses.
```
libsigcplusplus/docs/docs/manual/libsigc_manual.xml is also a DocBook 5.0 document.
It also benefits from installing the docbook5-xml and docbook-xsl packages.
It's slow and error prone to build the documentation without them.
(It sometimes works, though. That's why they are not required packages.)
I'll add some info in libsigcplusplus/README.md.
