### ISSUE TITLE
Remove [[no_discard]] from constructors

### ISSUE THREAD

**Issue by vadimgrn** [libsigcplusplus/libsigcplusplus#102]
scoped_connection.h has several constructors that are decorated with [[no_discard]]. It makes no sense for constructors and should be removed. Compilers generate warnings for them. If warnings are treated as errors, it will break a build.

P.S. You overuse [[no_discard]]. Use it only for functions that allocate memory or resources that must be released.

**Comment by kjellahl** [comment]
@db-src Daniel, you added the [[nodiscard]] attributes. Comments?

According to https://en.cppreference.com/w/cpp/language/attributes/nodiscard
the C++ standard has been changed slightly concerning [[nodiscard]] in constructors.
See the _Defect reports_ section.

Can we remove the problematic [[nodiscard]] attributes from scoped_connection.h?

**Comment by db-src** [comment]
As that link states [[nodiscard]] is applied to constructors since C++17 as a defect report. We require C++17. So this is a limitation of the user's implementation I would think.

You can remove them if you want. OP can also provide a citation for their recommendation when not to use...
