### ISSUE TITLE
3.6.0: warning #1011: missing return statement at end of non-void function

### ISSUE THREAD

**Issue by vadimgrn** [libsigcplusplus/libsigcplusplus#103]
Any use of sigc::bind generates a warning that breaks a build.
Compiler GCC 9.4, glibc 2.33, sigc++ 3.6.0

For example, this call will produce following messages
`sigc::bind( sigc::mem_fun(this, &kms_connector_t::page_flip_complete),                       buf));`

`/home/vadym/qsys/x86_64-linux-gnu/install/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_transform_each.h(87): warning #1011: missing return statement at end of non-void function "sigc::internal::detail::tuple_transform_each_impl<T_transformer, size_from_index>::tuple_transform_each(T_current &&, T_original &) [with T_transformer=sigc::internal::TransformEachInvoker, size_from_index=1UL, T_current=std::tuple<sigc::bound_argument<gfx::kms_scan_buffer_t>> &,
T_original=std::tuple<sigc::bound_argument<gfx::kms_scan_buffer_t>>]"
}
^
detected during:
instantiation of "decltype(auto) sigc::internal::detail::tuple_transform_each_impl<T_transformer, size_from_index>::tuple_transform_each(T_current &&, T_original &) [with T_transformer=sigc::internal::TransformEachInvoker, size_from_index=1UL, T_current=std::tuple<sigc::bound_argument<gfx::kms_scan_buffer_t>> &, T_original=std::tuple<sigc::bound_argument<gfx::kms_scan_buffer_t>>]" at line 104
instantiation of "decltype(auto) sigc::internal::tuple_transform_each<T_transformer,T>(T &&) [with T_transformer=sigc::internal::TransformEachInvoker, T=std::tuple<sigc::bound_argument<gfx::kms_scan_buffer_t>> &]" at line 191 of "/home/vadym/qsys/x86_64-linux-gnu/install/usr/include/sigc++-3.0/sigc++/adaptors/bind.h"
instantiation of "decltype(auto) sigc::bind_functor<-1, T_functor, T_type...>::operator()(T_arg &&...) [with T_functor=sigc::bound_mem_functor<void (gfx::kms_connector_t::*)(unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t), unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t>, T_type=<gfx::kms_scan_buffer_t>, T_arg=<sigc::type_trait_take_t<unsigned int>, sigc::type_trait_take_t<uint64_t={__uint64_t={unsigned long}}>>]" at line 155
of "/home/vadym/qsys/x86_64-linux-gnu/install/usr/include/sigc++-3.0/sigc++/functors/slot.h"
instantiation of "T_return sigc::internal::slot_call<T_functor, T_return, T_arg...>::call_it(sigc::internal::slot_rep *, sigc::type_trait_take_t<T_arg>...) [with T_functor=sigc::bind_functor<-1, sigc::bound_mem_functor<void (gfx::kms_connector_t::*)(unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t), unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t>, gfx::kms_scan_buffer_t>, T_return=void, T_arg=<unsigned int,
uint64_t={__uint64_t={unsigned long}}>]" at line 161 of "/home/vadym/qsys/x86_64-linux-gnu/install/usr/include/sigc++-3.0/sigc++/functors/slot.h"
instantiation of "sigc::internal::hook sigc::internal::slot_call<T_functor, T_return, T_arg...>::address() [with T_functor=sigc::bind_functor<-1, sigc::bound_mem_functor<void (gfx::kms_connector_t::*)(unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t), unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t>, gfx::kms_scan_buffer_t>, T_return=void, T_arg=<unsigned int, uint64_t={__uint64_t={unsigned long}}>]" at line 245 of
"/home/vadym/qsys/x86_64-linux-gnu/install/usr/include/sigc++-3.0/sigc++/functors/slot.h"
instantiation of "sigc::slot<T_return (T_arg...)>::slot(const T_functor &) [with T_return=void, T_arg=<unsigned int, uint64_t={__uint64_t={unsigned long}}>, T_functor=sigc::bind_functor<-1, sigc::bound_mem_functor<void (gfx::kms_connector_t::*)(unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t), unsigned int, uint64_t={__uint64_t={unsigned long}}, gfx::kms_scan_buffer_t>, gfx::kms_scan_buffer_t>]" at line 360 of "src/kms.cpp"`

**Comment by kjellahl** [comment]
sigc::bind() is used in many test cases in sigc++/tests. AFAIK it has not generated
warnings before, neither with gcc nor with clang or MSVC.

Excerpt from gcc 9.4's long warning:
include/sigc++-3.0/sigc++/tuple-utils/tuple_transform_each.h(87): warning #1011: missing return statement at end of non-void function

The function that ends at tuple_transform_each.h(87) looks like this:
```
constexpr static decltype(auto) tuple_transform_each(.....)
{
  if constexpr (.....)
  {
    .....
    return .....;
  }
  else
  {
    .....
    if constexpr (.....)
    {
      .....
      return .....;
    }
    else
    {
      .....
      return .....;
    }
  }
}
```
I don't understand why another `return` is needed.

I tried to add a `return` statement at the end of the function, outside the `if`
statements. That generates error messages from gcc 13.2.0 and clang 16.0.6.
The problem is that the return type is declared `decltype(auto)`, i.e.
the `return` statement determines the return type. You have to know which one of
the 3 original `return` statements is executed. The extra (seemingly unnecessary)
`return` statement must have the same type as the really executed `return` statement.
At least that's how I interpret the error messages.

It's surprising that gcc 9.4 can be too old. According to https://gcc.gnu.org/releases.html
it was released 2021-06-01. gcc 9.1 was released 2019-05-03. tuple_transform_each.h
has been around earlier than that.

**Comment by vadimgrn** [comment]
I see. I'll try a tiny test program tomorrow. May be it's misconfiguration during the upgrade.

**Comment by kjellahl** [comment]
gcc has the compiler option -Wreturn-type. From its description:

>Also warn about any return statement with no return value in a function whose
>return type is not void (falling off the end of the function body is considered
>returning without a value).

This option is enabled by -Wall. Perhaps you can silence it by adding -Wno-return-type.

**Comment by vadimgrn** [comment]
I can't, it is a huge project with thousands files and different architectures. Nobody will allow to do that.

**Comment by vadimgrn** [comment]
This is icpc-core2 Intel C++ compiler, not GCC.
