### ISSUE TITLE
docs should link to relative doxygen.css

### ISSUE THREAD

**Issue by jbicha** [libsigcplusplus/libsigcplusplus#12]
[docs/index.html](https://github.com/libsigcplusplus/libsigcplusplus/blob/master/docs/docs/index.html#L6) uses an absolute path to point to the stylesheet at http://library.gnome.org/devel/libsigc++/stable/doxygen.css

Please use a relative link so that when that page is viewed locally, it doesn't need to fetch a file from the Internet.

_This was discovered with Debian's lintian tool._

**Comment by kjellahl** [comment]
Is the docs/index.html file used anywhere?
It was once linked to from docs/website/doc.shtml, the predecessor of docs/doc.md.

I assume that docs/index.html can be removed. I would appreciate Murray's opinion.
Can I remove docs/index.html?

**Comment by murraycu** [comment]
I think it's meant to be just a starting page for installed documentation. But I don't know if we really need that, and I don't like maintaining a separate page that nobody will actually look at much. People can still look in the manual/ and reference/ sub-directories.

I've removed it:
https://github.com/libsigcplusplus/libsigcplusplus/commit/cfcf973873e277aad81e340af9136f685e60c225
