### ISSUE TITLE
Include build instructions and add Travis

### ISSUE THREAD

**Issue by Fohlen** [libsigcplusplus/libsigcplusplus#14]
It would be amazing to document the various build instructions (as far as I can see both `automake` and `cmake` are supported) in a `BUILDING.md` at least. Once these are settled then a `.travis.yml` could be added to test `libsigc++` automatically. I would be willing to aid in testing with  `OSX` (thus far I couldn't compile the examples) if necessary.

Any input on how I can help is appreciated! This library is great!

**Comment by murraycu** [comment]
It would still be nice to have some (free of cost) CI.

**Comment by murraycu** [comment]
We are now using the new GitHub Actions to build after every push, so I think I can close this.

Please feel free to suggest improvements to how I've setup the GitHub Actions (see .github/).
