### ISSUE TITLE
std::result_of is deprecated

### ISSUE THREAD

**Issue by kjellahl** [libsigcplusplus/libsigcplusplus#19]
According to https://en.cppreference.com/w/cpp/types/result_of `std::result_of<>` is
deprecated in C++17 and will be removed in C++20. It's used in sigc++/tuple-utils/tuple_transform_each.h.
It looks like it's replaced by `std::invoke_result<>`.

I tried to replace `result_of` by `invoke_result` in tuple_transform_each.h, but it's
not as easy as that. `make check` resulted in several compile-time errors.
The first error is
```
/home/kjell/checkout/gnome/libsigcplusplus/sigc++/tuple-utils/tuple_transform_each.h:49:81: error: no type named ‘type’ in ‘struct std::invoke_result<int& (*(sigc::bound_argument<int>&))(sigc::bound_argument<int>&)>’
         &T_transformer<from_element_type>::transform)(from_element_type&)>::type;
                                                                                 ^
/home/kjell/checkout/gnome/libsigcplusplus/sigc++/tuple-utils/tuple_transform_each.h:51:14: error: no type named ‘type’ in ‘struct std::invoke_result<int& (*(sigc::bound_argument<int>&))(sigc::bound_argument<int>&)>’
         std::tuple<to_element_type>(T_transformer<from_element_type>::transform(std::get<index>(t_original)));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kjellahl** [comment]
std::invoke_result<> requires a different syntax than std::result_of<>,
std::invoke_result<f, x> compared to std::result_of<f(x)>.
With the following small change in tuple_transform_each.h, all tests in
`make check` pass.
```C++
-      using to_element_type = typename std::result_of<decltype (
-        &T_transformer<from_element_type>::transform)(from_element_type&)>::type;
+      using to_element_type = typename std::invoke_result<decltype (
+        &T_transformer<from_element_type>::transform), from_element_type&>::type;
```
@murraycu is it okay that I push such a fix? You've written this code. Perhaps you
can easily see if the fix might cause any problems.

**Comment by murraycu** [comment]
Go for it. Thanks.
