### ISSUE TITLE
Tag 2.10.0 moved

### ISSUE THREAD

**Issue by afett** [libsigcplusplus/libsigcplusplus#21]
Hi, with a forced update around Feb. 10th. The tag 2.10.0 moved from commit:

commit 83f1e2fe7855f85af570b9653903d2c426d67e72
Author: Murray Cumming <murrayc@murrayc.com>
Date:   Tue Sep 20 12:13:23 2016 +0200

    2.10.0

to

commit 9e5e38c40636be148e1dd60eb3b167d05d84f4be
Author: Murray Cumming <murrayc@murrayc.com>
Date:   Wed Mar 16 12:35:55 2016 +0100

    test_retype: Add test of R(Args...) syntax.

I see, that the original commit is no longer present on master but still lives on branch libsigc++-2-10.
Could you maybe update the 2.10.0 tag accordingly?

**Comment by kjellahl** [comment]
Tag 2.99.10 is also misplaced. It is at

commit a246891c1cf780133861f01d911e0f7de3234986
Author: Murray Cumming <murrayc@murrayc.com>
Date:   Sat Mar 10 15:37:43 2018 +0100

    website: Correct website source link.

but should be at

commit 8116ff70fa44044d944f6d9790e0d7e4c29b1b0b
Author: Murray Cumming <murrayc@murrayc.com>
Date:   Wed Jan 10 22:48:03 2018 +0100

    2.99.10

I can't find any information who has misplaced these tags. Can someone, who knows
git better than I do, find such information?

>I see, that the original commit is no longer present on master but still lives on branch libsigc++-2-10.

Has it ever been present on master? I think it was commited to libsigc++-2-10
after the libsigc++-2-10 branch was created. Branched from libsigc++-2-8, I think.

**Comment by kjellahl** [comment]
Why are there only 5 tags? I would expect at least 60. Have lots of tags been
removed? Did they disappear when libsigc++ was moved to GitHub, or have they
disappeared later?

**Comment by kjellahl** [comment]
The documentation of `git tag` strongly discourages ever moving or deleting
a tag that has been pushed. Here someone seems to have done just that.
I'm not sure the best thing to do would be to move the tags once again.
Instead, I propose that I add add new tags, called `2.10.0really` and `2.99.10really`
at the right commits. That's how accidentally misplaced tags have been handled
in glibmm and gtkmm. Comments?

**Comment by afett** [comment]
Well If there's a "trusted" repo (or a number of identical ones) somewhere containing the state from before the forced push I myself wouldn't see a problem in restoring them here. But if thoses arn't available I could live with your suggested solution, too.

**Comment by afett** [comment]
By the way I still have a copy a repo which was probably synced with the gnome repo and I does indeed contain around 60 tags. I can make that available in case that helps with restoring tags.

**Comment by kjellahl** [comment]
It's a mystery, these moved and removed tags. Who does such a thing, and why?
In most cases you can see who has done what in a git repository, but in this case
I have not been able to find such info.

>By the way I still have a copy of a repo which was probably synced with the gnome repo
>and it does indeed contain around 60 tags. I can make that available in case that helps
>with restoring tags.

Yes, please, that would be fine. Do you know if it was synced with git.gnome.org
before the move to GitHub, or with github.com? Unfortunately I updated my own
local copy with `git pull` after the tags had been destroyed, but before I saw
this issue. I haven't payed much attention to tags before, just added one when
I've made a release.

I don't promise to recreate all 60 or so tags. I guess each one must be added manually.

**Comment by kjellahl** [comment]
@afett I've looked at some forked copies of libsigcplusplus in pull requests, one in an
open PR, three in closed PRs. All of them were probably forked well before Feb 10.
They all have the 2.10.0 and 2.99.0 at the same erroneous locations as
https://github.com/libsigcplusplus/libsigcplusplus. Are you sure these tags have
ever been correct after the move from git.gnome.org to GitHub?

@murraycu Do you know anything about misplaced and removed tags? Have you got
a copy of libsigcplusplus, cloned from GitHub but not updated in February 2019?

**Comment by kjellahl** [comment]
I have a local clone of libsigcplusplus that follows the libsigc++-2-10 branch.
The only files in the .git directory that have been changed after 2019-01-23 are
.git/config and .git/FETCH_HEAD. I don't know where git stores information about
tags, but I doubt that it's in one of these files. The 2.10.0 and 2.99.10 tags
are just as misplaced here as in every other clone of libsigcplusplus that I've seen.

Are you sure that the 2.10.0 tag was moved "around Feb. 10th"? Is it possible
that the 2.10.0 and 2.99.10 tags were misplaced, and many other tags removed, when
libsigcplusplus was moved from git.gnome.org about a year ago?

**Comment by afett** [comment]
Sorry for the delay. Well I can't really confirm that the tags where ever on github. I have a local mirror (aka git clone --mirror) here which used to point to the gnome repo and later was switched to the github one. All my repos are clones of this mirror. I'm sure, that the 2.10.0 tag at one point referenced the correct commit as we do automated builds from this. On the date mentioned I noticed a forced update when pulling from the mirror and the build broke, because the tag changed to a pre 2.10 version. When looking at another clone from the mirror I found the tags pointing at different commits.

I'm still trying to get my "state" of the repo with the original tags into a condition where I can push it to github, but it's not easy as it references objects in the local mirror and I'm not a git expert either.

**Comment by murraycu** [comment]
I have no idea if these tags were ever on github. What problem are we trying to solve here?

**Comment by afett** [comment]
@murraycu I just noticed, that the 2.10.0 tag (here on github) does in fact not point to version 2.10.0 but a seemingly random commit earlier. That's all I wanted to tell you, just in case that was an unnoticed accident. I have since moved on to 2.10.1 so it doesn't really concern me anymore.

**Comment by kjellahl** [comment]
>I'm still trying to get my "state" of the repo with the original tags into a condition
>where I can push it to github, but it's not easy as it references objects in the local
>mirror and I'm not a git expert either.

Don't spend too much time on that. The issue is not that serious. I can move the
misplaced tags or add 2.10.0really and 2.99.10really. I can also add a few missing tags,
but not 60. It's easy to see where they should have been.

@murraycu Is it okay that I move the two misplaced tags? Or do you prefer that I add
"really" tags and don't touch existing tags, however wrong they are?

**Comment by murraycu** [comment]
@kjellahl Go for it. I trust your judgement. Thanks,

**Comment by kjellahl** [comment]
I have moved tags 2.10.0 and 2.99.10 to where they shall be, and added 2.99.9, 2.99.8 and 2.8.0.
