### ISSUE TITLE
Build failure with libc++

### ISSUE THREAD

**Issue by jefftrull** [libsigcplusplus/libsigcplusplus#25]
Building using CMake on my OSX box, as well as using clang on Linux (with stdlib=libc++) fails with static_asserts in test_tuple_transform_each.cc ("unexpected transform_each()ed tuple type"). Upon further investigation, it appears that

`decltype(t_transformed)` is `tuple<const string, const string, const string>`

while

`decltype(t_expected)` is `tuple<string, string, string>`

I wonder if there is a `std::remove_cv` missing somewhere.

**Comment by kjellahl** [comment]
`std::tuple_cat<>()` behaves differently in libc++ and libstdc++. Here's a code
fragment from a test case:
```C++
  int i1 = 1;
  const int ci2 = 2;
  auto t1 = std::make_tuple(i1, ci2);
  const auto ct2 = std::make_tuple(i1, ci2);
  auto t3 = std::tuple<int, const int>(i1, ci2);
  auto t_cat = std::tuple_cat(t1, ct2, t3);
```
With libstdc++ the type of `t_cat` is  
std::tuple<int, int, int, int, int, const int>

With libc++ it's  
std::tuple<int, int, const int, const int, int, const int>

The difference is that if a `const std::tuple` is fed to `std::tuple_cat`,
with libc++ all created tuple elements coming from the const tuple, become const.
Not so with libstdc++. Which is correct? I've tried to figure out by reading
a small part of the C++ standard. But as you probably know, that standard is
hard reading. I'm not sure which is correct, but I guess it's libc++.

sigc::internal::tuple_transform_each<>() contains two calls to std::tuple_cat
with const tuples as parameters. If I change 4 `const auto` to `auto` in
tuple_transform_each.h, the test passes. I'll fix this issue that way, unless
someone has a better idea.

**Comment by K-ballo** [comment]
libstdc++ is right, libc++ was recently [fixed](https://github.com/llvm-mirror/libcxx/commit/cc57a78190b8526e23e7979c5ef0859c2bb72366#diff-b7bdf907b73de8b57112566afeaebf35).

**Comment by kjellahl** [comment]
Since the bug is in libc++ and it has been fixed, I won't fix anything in libsigc++.

This issue can be kept open until it can be tested with a fixed and easily available
version of libc++.

**Comment by murraycu** [comment]
I guess we might need a workaround in libsigc++ if this libc++ bug is, and will be, widely distributed.

**Comment by jefftrull** [comment]
That would be great! I'm maintaining a fork of libsigc++ for this very reason.

**Comment by murraycu** [comment]
I guess this would need a compiler check at configure time, so we can use #ifdef . glibmm still has some examples of m4 macros this with autoconf:
https://github.com/GNOME/glibmm/tree/master/build

But we are trying to keep the CMake build too, which would make it awkward.

**Comment by kjellahl** [comment]
Is a configure-time check necessary? Can't we just change `const auto` to `auto`
unconditionally in tuple_transform_each.h, like I tested in https://github.com/libsigcplusplus/libsigcplusplus/issues/25#issuecomment-508120637?

**Comment by murraycu** [comment]
Sure. That sounds fine, with a comment please. Thanks

**Comment by kjellahl** [comment]
I have changed `const auto` to `auto` in sigc++/tuple-utils/tuple_transform_each.h.
All test cases in `make check` pass with `clang++ -stdlib=libc++`.

std::tuple_cat() is also used with const std::tuple as input data in
sigc++/functors/bind.h and sigc++/functors/hide.h. It doesn't break `make check`.
I don't know if can break anything else. I keep it as it is unless someone says
it should be changed.
