### ISSUE TITLE
libsigc++-2-10 branch is outdated

### ISSUE THREAD

**Issue by lantw44** [libsigcplusplus/libsigcplusplus#3]
It seems that the `libsigc++-2-10` branch on GitHub is older than the branch on GNOME Git. Is it expected? `git status` says the version on GitHub misses 36 commits.

```
$ git status
On branch libsigc++-2-10
Your branch is ahead of 'origin/libsigc++-2-10' by 36 commits.
```

**Comment by murraycu** [comment]
Thanks for noticing. I have pushed the recent changes to that branch now. Sorry that it wasn't correct from the beginning of the move.

**Comment by lantw44** [comment]
I confirmed that `libsigc++-2-10` branch on GitHub is now up to date.
