### ISSUE TITLE
Tutorial is not up-to-date with new sigc::signal template parameter style

### ISSUE THREAD

**Issue by denisw** [libsigcplusplus/libsigcplusplus#59]
The tutorial explains that signal parameters can be specified as extra template argument, e.g. `sigc::signal<void, std::string>`. However, when I try this I get a compile error:

```
error: implicit instantiation of undefined template 'sigc::signal<void, std::__1::basic_string<char> >'
```

Looking at the code in this repo's `examples/` folder, it seems like nowadays I should write `sigc::signal<void(std::string)>` instead. It would be great if the tutorial could be updated accordingly so that others don't have to go through the same confusion. Thanks!

**Comment by kjellahl** [comment]
The syntax of the template parameters are different in libsigc++2 and libsigc++3.
The tutorial in libsigc++3 had not been updated. It's fixed now in the git repo.

**Comment by denisw** [comment]
Wow, that was fast - thanks a lot! 🙂
