### ISSUE TITLE
C++17 required?

### ISSUE THREAD

**Issue by only-a-ptr** [libsigcplusplus/libsigcplusplus#6]
Hello.

The README file says `Compatible compilers must support C++14`.

However, several headers under `sigc++/tuple-utils` contain nested namespaces, which is a C++17 feature. It was added quite recently by current maintainer: https://github.com/libsigcplusplus/libsigcplusplus/commit/1759faf552248373714acc573b55421e86cb94cc - the need for C++17 nested namespaces is explicitly mentioned in the comment.

Does this mean the README is out of date?

Thank you.

**Comment by kjellahl** [comment]
Yes, the README file is out of date. I'll fix it.
The libsigc++ version in the master branch requires C++17.
sigc++-2.0 in e.g. the libsigc++-2-10 branch requires just C++11.
