### ISSUE TITLE
can't Compile by visual c++ with readme.txt

### ISSUE THREAD

**Issue by babyaaaaaa** [libsigcplusplus/libsigcplusplus#60]
would you add some detailed in readme.txt, thanks

**Comment by fanc999** [comment]
Hi,

Can you let me know the following:

*  What version(s) of libsigc++ are you using, or are you using a GIT checkout (if so, which branch and which commit are you using, if not the tip of the branch)

*  What are the error messages or issues you are encountering?

The readme.txt in MSVC_NMake/ was updated quite recently, so I'll be glad to know where I can do better in those :)

With blessings, and cheers!

**Comment by babyaaaaaa** [comment]
i use win10 vs2019, follow the libsigc++-3.0.3\MSVC_NMake\README.txt,  
input>>
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\Hostx86\x86>nmake.exe /f D:\work\windows\audit\lib\libsigc++-3.0.3\MSVC_NMake\Makefile.vc CFG=release PREFIX="D:\work\windows\audit\lib\libsigc++303"
echo>>
D:\work\windows\audit\lib\libsigc++-3.0.3\MSVC_NMake\detectenv-msvc.mak(57) : fatal error U1050:
This Makefile is only for Visual Studio 2008 and later.
You need to ensure that the Visual Studio Environment is properly set up
before running this Makefile.
Stop.

**Comment by fanc999** [comment]
Hi @babyaaaaaa,

I see, it seems that 3.0.3 was released before the needed updates were added...
The next release of libsigc++-3.x will contain the needed fixes for the build to work on Visual Studio 2019.

With blessings, and cheers!
