### ISSUE TITLE
Static build support

### ISSUE THREAD

**Issue by brukted** [libsigcplusplus/libsigcplusplus#63]
I was trying to port libsigc-3 to vcpkg  and I have noticed that libsigc-3 uses shared build by default is there any reason to this? Does libsigc-3 support static build?

**Comment by kjellahl** [comment]
I haven't tried, but it should be possible to build a static library.
Do you build with Autotools or with Meson?

With Autotools, add the `--enable-static` argument to `./configure`.  
To get a list of configure arguments: `./configure --help`

With Meson, `meson configure -Ddefault_library=static` or `meson configure -Ddefault_library=both`  
To get a list of options: `meson configure`

Why shared library? To save memory space. The library is not copied to each application
that uses it. But I admit that it's not important for libsigc which consists
mostly of template functions, which are included in the using applications anyway.

**Comment by brukted** [comment]
Thanks!
