### ISSUE TITLE
how to use emit in multithread?

### ISSUE THREAD

**Issue by babyaaaaaa** [libsigcplusplus/libsigcplusplus#64]
when i use the emit in multithread it throw exception,  how could i use emit in mutlithread ?

**Comment by kjellahl** [comment]
libsigc++ is not thread-safe. There are things you can't safely do if more than
one thread is involved.

It's impossible to say what you shall do from your short question. I suppose that
emit() shall trigger calls to some slots. What do those slots do? Does some slot
throw an exception even if it's called in other ways (without using emit()).
Which exception is thrown? From where?

**Comment by babyaaaaaa** [comment]
suppose that I have a receiver which receive data from socket or http client, and then post the data to a thread pool to 
handle the data:

class receiver
{
public:
    receiver(int num_threads) : work_pool_(num_threads)
    {

    }
public:
    sigc::signal<void(std::shared_ptr<std::string>)> signal_data_;

public:
    void run()
    {
        while (true) 
        {

            auto data = std::make_shared<std::string>("test data");
            boost::asio::post(work_pool_, [this, data]() {
                {
                    //std::lock_guard lk(mtx_);   //is it must be locked ? are there some other option for multithread in this case ？
                    signal_data_.emit(data);
                }
                
            });
        }
    }
private:
    boost::asio::thread_pool work_pool_;
    std::mutex mtx_;
};


class worker
{
public:
    void do_work(std::shared_ptr<std::string> data)
    {
        std::cout << "do_work thread:" << std::this_thread::get_id() << ":" << *data << std::endl;
    }
};

int main()
{
    receiver receiver_(10);
    worker worker_;
    receiver_.signal_data_.connect(sigc::mem_fun(worker_, &worker::do_work));
    receiver_.run();

    getchar();
    return 0;
}

**Comment by babyaaaaaa** [comment]
it crash on this:

    for (const auto& slot : slots)   //////////////////////here
    {
      if (slot.empty() || slot.blocked())
        continue;

      (sigc::internal::function_pointer_cast<call_type>(slot.rep_->call_))(slot.rep_, a...);
    }

**Comment by kjellahl** [comment]
I haven't tested your code, and I don't know what boost::asio::post() does.
I'm partly guessing here.

The repeated calls to boost::asio::post() make `signal_data_.emit(data)` be called
simultaneously in different threads. That's risky, and will surely cause a crash
sooner ar later. Each call to sigc::signal<>::emit() makes temporary modifications
to the list of connected slots. That's not a thread-safe operation. If you're interested,
you can look at what sigc::internal::temp_slot_list does.

Conclusion: You can't call emit() on the same signal simultaneously in different threads.

You ask if a std::lock_guard would help. Have you tried? I think it helps.
On the other hand, I suppose it would make the thread pool meaningless. You want
work to be going on simultaneously in all processor cores, don't you?
In your simple example, emit() seems unnecessary. You can call worker::do_work()
directly from the lambda expression that you send to boost::asio::post().
