### ISSUE TITLE
Small issues when building on Windows with MSVC

### ISSUE THREAD

**Issue by xclaesse** [libsigcplusplus/libsigcplusplus#71]
Since I wrote a blog post about building GTK4 applications on Windows, someone asked about gtkmm, so I gave it a try.
https://www.collabora.com/news-and-blog/blog/2021/04/29/build-your-own-application-with-gtk4-as-a-meson-subproject/

I noticed a few things that can be improved:
- Fallback for `find_program('mm-common-get', required: false)` does not work. If the program is not required Meson prefer not using the fallback subproject. Changing it to `find_program('mm-common-get', required: maintainer_mode)` would make more sense since you `error()` just below anyway.
- Building doc requires many extra deps (perl, etc), would be nice to make that optinal by default using a `feature` option that defaults to `auto`.
- When disabling documentation, `'doxytagfile': tag_file.full_path()` fails because tag_file is not defined.

**Comment by xclaesse** [comment]
> * Building doc requires many extra deps (perl, etc), would be nice to make that optinal by default using a `feature` option that defaults to `auto`.
> 
> * When disabling documentation, `'doxytagfile': tag_file.full_path()` fails because tag_file is not defined.

I don't know where to report cairomm issues, but those 2 are copy/pasted into cairomm, so should be changed there too ideally.

**Comment by kjellahl** [comment]
> I don't know where to report cairomm issues

Report at https://gitlab.freedesktop.org/cairo/cairomm/-/issues  
But you don't have to do that in this case. All 3 items in this issue are
identical or very similar in libsigc++, cairomm, glibmm, atkmm, pangomm, gtkmm
and libxml++. (Atkmm and libxml++ are not used by gtkmm4.)

> Fallback for find_program('mm-common-get', required: false) does not work. If the program is not required Meson prefer not using the fallback subproject. Changing it to find_program('mm-common-get', required: maintainer_mode) would make more sense since you error() just below anyway.

Don't you find my error() message more informative than Meson's error message,
just telling that mm-common-get could not be found?

Which version of Meson do you use? Only versions >=0.55.0 understand the [provide]
section in mm-common.wrap.

**Comment by xclaesse** [comment]
> Don't you find my error() message more informative than Meson's error message,
> just telling that mm-common-get could not be found?

It's true that error message is more informative, I agree.

> Which version of Meson do you use? Only versions >=0.55.0 understand the [provide]
> section in mm-common.wrap.

I know, I'm the one who implemented that feature in meson, I'm using master :D

The problem here is Meson will not search in the [provide] section for optional programs `find_program('mm-common-get', required: false)`, it will look for fallback only if `required: true`. I realize it's not documented behaviour, it's only documented in the `dependency()` case: https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section.

Also, `dependency()` has `allow_fallback: true` argument that can be added to change that behaviour, but `find_program()` does not unfortunately.

**Comment by kjellahl** [comment]
I have created PR #72 with possible fixes for 2 of your 3 issues. Comments?
