### ISSUE TITLE
Meson issues on 2.10.4

### ISSUE THREAD

**Issue by IngwiePhoenix** [libsigcplusplus/libsigcplusplus#73]
In order to port a RGSS player (RPG Maker games) to the Playstation Vita, I need to get this library working first.

Since the [mkxp]() project relies on `pkg-config` returning information for `sigc++-2.0`, I needed to use an older version, since the newer 3.0 versions do not produce this file anymore.

The following problem arose:
```
The Meson build system
Version: 0.49.2
Source dir: /opt/libsigcplusplus
Build dir: /opt/libsigcplusplus/out
Build type: native build

meson.build:63:64: ERROR:  Expecting eof got eol_cont.
is_dist_check = project_source_root.contains('dist-unpack') and \
                                                                ^

A full log can be found at /opt/libsigcplusplus/out/meson-logs/meson-log.txt
```

The log is attached.
[meson-log.txt](https://github.com/libsigcplusplus/libsigcplusplus/files/6539422/meson-log.txt)

The Playstation Vita homebrew toolchain (VITASDK) is a GCC based, cross-compiling toolchain running in WSL2 on Windows, even `pkg-config` is prefixed.

How can I work around that? I think my meson install might be too new... but, I have no experience with meson. And, autotools failed because `mm-common-prepare` is missing.

**Comment by kjellahl** [comment]
> I think my meson install might be too new.

On the contrary, Meson version 0.49.2 is too old. libsigc++ requires 0.54.0 or newer.
I'm surprised that Meson does not tell you that.

If you want to build with autotools, starting from a tarball made with meson,
you must have mm-common installed. The mm-common-prepare command is included in
the mm-common package.

**Comment by kjellahl** [comment]
Sorry, I was too quick when I wrote the previous comment. I assumed that you had
used the latest version of libsigc++2, which is 2.10.7. Version 2.10.4 requires
meson 0.50.0 or newer. Then it's strange that meson reports that line 63 is broken and is
```
is_dist_check = project_source_root.contains('dist-unpack') and \
```
That's line 63 in libsigc++ 2.10.7, but line 61 in 2.10.4.
Have your meson.build file been corrupted?

**Comment by kjellahl** [comment]
Can you please double-check your meson.build file. Has it been corrupted?
I don't understand why Meson (even if it's the wrong version of Meson) expects
end-of-file at line 63. A correct meson.build file in the source root directory
is several hundred lines long.
