### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by delauflahm** [libsigcplusplus/libsigcplusplus#76]
Hey,

I don't need it anymore - how can I uninstall `libsigcplusplus`?

**Comment by kjellahl** [comment]
How have you installed it?

If you've used the package manager in a Linux distribution, I suppose the
package manager can uninstall it.

If you've built from source with Meson, use *ninja uninstall*. When I tested this,
I found that if libsigcplusplus has been built and installed by jhbuild,
ninja uninstall does not work. If you've used jhbuild, I guess you have to remove
installed files manually.

If you've built from source with Autotools, use *make uninstall*.

**Comment by delauflahm** [comment]
I've installed libsigcplusplus via `make install`.
When I run the command `make uninstall` this shows up:

> user@pc:home/user//Downloads/libsigcplusplus$ make uninstall
> CMake Error at cmake_uninstall.cmake:2 (message):
> Cannot find install manifest:
> /home/user/Downloads/libsigcplusplus/install_manifest.txt
> make[3]: *** [CMakeFiles/uninstall.dir/build.make:76: CMakeFiles/uninstall] Error 1
> make[2]: *** [CMakeFiles/Makefile2:236: CMakeFiles/uninstall.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/uninstall.dir/rule] Error 2
> make: *** [Makefile:194: uninstall] Error 2
> user@pc:home/user//Downloads/libsigcplusplus$

**Comment by kjellahl** [comment]
Your error messages tell me that you've used CMake. From README.md:
```
The CMake build is not used very often by the libsigc++ developers, but it
should work, and we would welcome improvements.
```

When I tested building, installing and uninstalling with CMake, it worked.
```
mkdir buildcmake
cd buildcmake
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnome -S ..
make
make install
make uninstall
```
The install_manifest.txt file is created by `make install`. It contains a list of installed files.
Did you run `make install` from the directory where you ran `make uninstall`?

**Comment by delauflahm** [comment]
> The install_manifest.txt file is created by make install. It contains a list of installed files.
> Did you run make install from the directory where you ran make uninstall?
Yes, I ran every command in the same directory.

**Comment by kjellahl** [comment]
You can try `make install` once again and hope that an install_manifest.txt file is created.
If it is, try to uninstall again.

**Comment by delauflahm** [comment]
Success
