### ISSUE TITLE
Can we have an automatically disconnecting 'RAII connection', equivalent of `boost::signals2::scoped_connection`?

### ISSUE THREAD

**Issue by db-src** [libsigcplusplus/libsigcplusplus#87]
I have a few times wanted a `connection` that automatically `disconnect()`s itself when it goes out of scope and is destructed, via RAII.

`boost::signals2` offers this:

> [boost::signals2::scoped_connection](https://www.boost.org/doc/libs/1_50_0/doc/html/boost/signals2/scoped_connection.html) — Limits a signal-slot connection lifetime to a particular scope.

It would be handy if we had the same here, not only because it's useful, but also because I believe `sigc++` was at one point based on the original `boost::signals` (?) and is at the outline level mostly compatible, perhaps with small changes... so this would hopefully be only a small bit of work to bring us up to feature par with it.

Would it be possible therefore for us to get a `sigc::scoped_connection` or similar?

If yes, I should be able to look at developing this, unless someone else wants to. :-)

Thanks in advance!

**Comment by kjellahl** [comment]
@db-src Are you still willing to make a sigc::scoped_connection class?

What do we do with functions that return a sigc::connection? For instance
sigc::signal::connect() and Glib::SignalProxy::connect(). Probably a bad idea to
add a scoped_connect() function for each connect() function. Better to have a
sigc::scoped_cońnection(const sigc::connection& con) constructor.

**Comment by kjellahl** [comment]
After a quick thought, I vote for disallowing copying.
If we allow copying, either the slot can be disconnected 
1. when any of the scoped connections is deleted, or
2. when the last scoped connection is deleted.

Case 1 is somewhat unintuitive, I think. Case 2 requires reference counting
which is unnecessarily complicated. Let's keep it fairly simple.

**Comment by db-src** [comment]
@kjellahl MR created, let me know what you think :-)
* https://github.com/libsigcplusplus/libsigcplusplus/pull/97
