### ISSUE TITLE
Slight issues in `sigc::connection` intro documentation

### ISSUE THREAD

**Issue by db-src** [libsigcplusplus/libsigcplusplus#88]
Currently it reads as:

```none
/** Convinience class for safe disconnection.
 * Iterators must not be used beyond the lifetime of the list
 * they work on. A connection object can be created from a
 * slot list iterator and may safely be used to disconnect
 * the referred slot at any time (disconnect()). If the slot
 * has already been destroyed, disconnect() does nothing. empty() or
 * operator bool() can be used to test whether the connection is
 * still active. The connection can be blocked (block(), unblock()).
 *
 * This is possible because the connection object gets notified
 * when the referred slot dies (notify()).
 *
 * @ingroup signal
 */
```

* `Convinience` is a typo!
* The remainder focuses only on slot iterators and even then is not terribly clear:
  * We may want to first talk about how, separate from slot iterator lifetime issues, `sigc::connection`s can be used to `disconnect()`, `block()`, _etc._ - and only after that mention how those abilities can help avoid issues with slot iterator validity.
  * It should perhaps be "_Slot iterators [link to info about accumulators somewhere] must not be used beyond..._" or something - currently just opening talking about "Iterators" without further qualification seems liable to confuse users.

Would it be possible to make this more general, clearer about slot iterators, _etc._?

**Comment by kjellahl** [comment]
This the description in sigc++2. The description in sigcc+3 is different and
shorter. The patch that changed the description has a commit message saying

> This no longer needs to (or can be) created from an iterator.

If you want a modification that applies only to sigc++2, please suggest how the
decumentation shall be changed. I can fix the typo, but not much more.
What about copying the description from sigc++3?
