### ISSUE TITLE
meson build fails because of invalid generated path

### ISSUE THREAD

**Issue by MrScriptX** [libsigcplusplus/libsigcplusplus#89]
When building using Meson, mm-common-get2 script fails because the generated path for pkgdatadir does not escape backslashes.

Here is the generated line : `pkgdatadir = os.path.join('D:\repos\libsigcplusplus\builddir\subprojects\mm-common', 'mm-common')`
And it should be :  `pkgdatadir = os.path.join('D:\\repos\\libsigcplusplus\\builddir\\subprojects\\mm-common', 'mm-common')`

I'm building on Windows. Maybe it affects how the path is generated.

**Comment by eli-schwartz** [comment]
Or maybe just use raw strings.

**Comment by fanc999-1** [comment]
Hi,

It seems that you are trying to build libsigc++-2.x?

Apparently this is actually not an issue in the `libsigcplusplus` project, but is in the `mm-common` subproject.  For an interim fix, open `$(top_srcdir)/subprojects/mm-common/meson.build`, and change line 316 from:
```
  conf_data_subproj.set('datadir_py', project_build_root)
```
to:
```
   conf_data_subproj.set('datadir_py', project_build_root.replace('\\','\\\\'))
```

Do note that if you are using `mm-common` as a subproject, you need to also pass in `-Dmm-common:use-network=true` when configuring the build.

With blessings, and cheers!

**Comment by fanc999-1** [comment]
For records: Upstream merge request: https://gitlab.gnome.org/GNOME/mm-common/-/merge_requests/7.

**Comment by kjellahl** [comment]
Chun-wei Fan's merge request has been merged to https://gitlab.gnome.org/GNOME/mm-common.
If it doesn't fix the problem, feel free to reopen this issue.
